export enum GoalObjective {
    Boycott = 'boycott',
    FinanciallySupportLocallyOwnedBusinesses = 'financially support locally owned businesses',
    EmotionallySupport = 'emotionally support',
    PeacefulDemonstrationFor = 'peaceful demonstration for black lives matter',
    PeacefulDemonstrationAgainst = 'peaceful demonstration against',
    SupportBlackLivesMatter = 'support black lives matter',
    SaveThePlanet = 'save the planet',
    EndSexism = 'end sexism',
    EndRacism = 'end racism',
    EndAnimalAbuse = 'end animal abuse',
    ReducePlastic = 'reduce plastic consumption',
    ReduceCarbonFootprint = 'reduce carbon footprint',
    ReduceAnimalProductConsumption = 'reduce animal product consumption',
};
