export enum PopcottGoalOutcomes {
    SupportBlackPeople = 'to support black people',
    SupportTransPeople = 'to support trans people',
    RaiseMoneyForAGoodCause = 'to raise money for a good cause',
    SupportAsianPeople = 'to support asian people',
    SupportBrownPeople = 'to support brown people',
    SupportGayPeople = 'to support gay people',
    SupportMinorityPeople = 'to support minority people',
    SupportWomen = 'to support women',
    StopMisinformation = 'to stop the spread of disinformation',
    SupportYourNeighborhood = 'to support your neighborhood',
    ProtectThePlanet = 'to protect the planet',
    FightForVotingRights = 'to support voting rights',
    EndSexism = 'to end sexism',
    EndRacism = 'to end racism',
    EndAnimalAbuse = 'to end animal abuse',
    EndPoliceAbuse = 'to end police abuse',
    EndChildAbuse = 'to end child abuse',
    ImproveMentalHealth = 'to improve mental health',
    LegalizeCannabis = 'to legalize cannabis',
    ProtectReproductiveRights = 'to protect reproductive rights',
    EndCovid19 = 'to end covid 19',
    PromotePositivity = 'to promote positivity',
};
