export enum PopcottGoalOutcomes {
    SupportBlackPeople = 'to support black people',
    SupportTransPeople = 'to support trans people',
    RaiseMoneyForAGoodCause = 'to raise money for a good cause',
    SupportAsianPeople = 'to support asian people',
    SupportBrownPeople = 'to support brown people',
    SupportGayPeople = 'to support gay people',
    SupportMinorityPeople = 'to support minority people',
    SupportWomen = 'to support women',
    StopMisinformation = 'to stop the spread of disinformation',
    SupportYourNeighborhood = 'to support your neighborhood',
    ProtectThePlanet = 'to protect the planet',
    FightForVotingRights = 'for equal voting rights',
    EndSexism = 'end sexism',
    EndRacism = 'end racism',
    EndAnimalAbuse = 'end animal abuse',
    EndPoliceAbuse = 'end police abuse',
    ImproveMentalHealth = 'improve mental health',
    LegalizeCannabis = 'legalize cannabis',
    ProtectReproductiveRights = 'protect reproductive rights',
    EndCovid19 = 'end covid 19',
};
